Remove guava dependency
jenkinsci/google-kubernetes-engine-plugin pull request #176
Opened 2021-03-26 16:17 UTC by alecharp

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2022-04-26 07:23 UTC, raul-arabaolaza approved these changes

2022-04-26 07:37 UTC, raul-arabaolaza requested changes
It is better to update the baseline also

2022-04-26 08:02 UTC, alecharp commented
Done @raul-arabaolaza

2022-10-19 10:41 UTC, alecharp commented
@raul-arabaolaza would this be merged?

2024-01-09 14:30 UTC, closed without merging